import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Header} from '@/components/Header';
import {Footer} from '@/components/Footer';
import {HeaderUsecase} from '@/components/Header/Header.usecase';
import {FooterUsecase} from '@/components/Footer/Footer.usecase';
import {DropDownActions} from '@/components/DropdownActions';
import {DropDownActionsUsecase} from '@/components/DropdownActions/DropdownActions.usecase';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-dvh flex flex-col justify-start antialiased`}>
        <Header {...HeaderUsecase} />
        <DropDownActions {...DropDownActionsUsecase} />
        {children}
        <Footer className='mt-auto' {...FooterUsecase} />
      </body>
    </html>
  );
}
